import Head from 'next/head';
import { Inter } from 'next/font/google';
import { FC } from 'react';

import styles from '../styles/Community.module.scss';

import Nav from '@/components/Nav';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

const Community: FC = () => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
        <main className={inter.className + ' ' + styles.main}>
        
        </main>
    </>
  );
};

export default Community;