import Head from 'next/head';
import { Inter } from 'next/font/google';
import { FC, useEffect } from 'react';

import Link from 'next/link';
import Image from 'next/image';

import boatImage from '../images/boat.png';
import flowerImage from '../images/flower.png';

import styles from '@/styles/Home.module.scss';
import Nav, { NavTypes } from '@/components/Nav';
import Footer from '@/components/Footer';
import { socials } from '@/utils/socials';

const inter = Inter({ subsets: ['latin'] });

const Home: FC = () => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="elley, geometry dash, gd, gameplay, russian, gp maker, discord, telegram, youtube" />   
        <meta property="description" content="💸💸💸Cool gameplay for your level in geometry dash for a reasonable price! 
        This page contains the social networks of Elley, have a nice chat!💬💬💬" />
        <meta name="Author" content="Савельев Егор Антонович" />
        <meta name="Copyright" content="Elley 2023" />
        <title>Elley | Geometry Dash GP Making 🔨</title>
        <link rel="icon" href="/favicon.ico" />
        {/* Facebook */}
        <meta property="og:locale" content="eng_Eng" />
        <meta property="og:title" content="Elley | Geometry Dash GP Making 🔨" />
        <meta property="og:description" content="💸💸💸Cool gameplay for your level in geometry dash for a reasonable price! 
        This page contains the social networks of Elley, have a nice chat!💬💬💬" />    
        <meta property="og:site_name" content="Elley | Geometry Dash GP Making 🔨" />
      </Head>
      <Nav type={NavTypes.transparent} />
      <main className={inter.className + ' ' + styles.main}>
        <section className={styles.intro}>    
          <div className={styles.content}>
            <Image src={flowerImage} alt="flowers, цветы" className={styles['flower']} />
            <Image src={boatImage} alt="boat, лодка" className={styles['boat']} />
            <div className={styles['intro-image']}>
              <div className={styles['intro-image__indicate']}></div>
            </div>
            <div className={styles['intro-description']}>
              <h1 className={styles.title}>🌩️ 
                Gameplay Request are <span className="animate-indicate">Open</span> 🌩️
              </h1>
              <div className={styles.socials}>
                {socials.map((social) => {
                  return (
                    <Link title={social.title} key={social.id} href={social.path}>
                      <div className={styles.social + ' ' + styles[`social__${social.title.toLowerCase()}`]}></div>
                    </Link>
                  );
                })}
              </div>
            </div>
          </div>   
        </section>
      </main>   
      <Footer/>
    </>
  );
};

export default Home;
